language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-750704754114"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

